---
- name: Create Gopherbot Install directory
  file:
    path: "{{ gopherbot_install_directory }}"
    state: directory
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
- name: Create Gopherbot history directory
  file:
    path: "{{ gopherbot_history_directory }}"
    state: directory
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
- name: Create Gopherbot file brain directory
  file:
    path: "{{ gopherbot_brain_directory }}"
    state: directory
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
- name: Create Gopherbot WorkSpace
  file:
    path: "{{ gopherbot_workspace_directory }}"
    state: directory
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
- name: Ensure Gopherbot config directory exists
  file:
    path: "{{ gopherbot_config_directory }}"
    state: directory
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
- name: Install EPEL for jq
  yum: name=epel-release
  when: ansible_distribution == "CentOS"
- name: Install required packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
  - unzip
  - jq
  - ruby
  - python
  - git
- stat:
    path: "{{ gopherbot_install_directory }}/lib"
  register: gopher_lib
- name: Download Gopherbot archive
  unarchive:
    src: "{{ gopherbot_archive }}"
    dest: "{{ gopherbot_install_directory }}"
    owner: "{{ gopherbot_user }}"
    group: "{{ gopherbot_group }}"
    mode: 0750
    remote_src: yes
  when: gopherbot_force_update or gopher_lib.stat.isdir is not defined
  register: gopher_install
- name: Add systemd unit file for Gopherbot
  template:
    src: gopherbot_service.j2
    dest: /etc/systemd/system/{{ gopherbot_service_name }}.service
    owner: root
    group: root
    mode: 0640
  register: unit
- name: Add environment file for secrets
  template:
    src: gopherbot_env.j2
    dest: /etc/gopherbot.env
    owner: root
    group: root
    mode: 0600
  register: unit
- name: Make sure daemon reloads on change
  systemd: daemon_reload=yes
  when: unit.changed
- name: Make sure Gopherbot runs on startup
  systemd: daemon_reload=yes name={{ gopherbot_service_name }} state=started enabled=yes
- name: Restart Gopherbot
  systemd: name={{ gopherbot_service_name }} state=restarted
  when: gopher_install.changed or unit.changed
